#!/usr/bin/env python3
from pathlib import Path

p=Path(__file__).resolve().parents[1]/'_site'/'index.html'
s=p.read_text(encoding='utf-8')

def repl(old,new,label):
    global s
    if old not in s:
        raise SystemExit(f'UI patch anchor missing: {label}')
    s=s.replace(old,new,1)

repl('.sc0{stroke:#d4d9df;stroke-width:.6;stroke-dasharray:2 2}', '.sc0{stroke:#d4d9df;stroke-width:.6;stroke-dasharray:2 2}.hg0{stroke:#aeb7c2!important}.hg5{stroke:#e9c46a!important;stroke-width:1.5!important}.hg10{stroke:#f4a261!important;stroke-width:1.8!important}.hg15{stroke:#e76f51!important;stroke-width:2.15!important}.hg20{stroke:#9b2226!important;stroke-width:2.5!important}.hunk{stroke:#d0d5dd!important;stroke-dasharray:2 2}', 'hill CSS')
repl('<div class="row"><div><div class="label">Street network</div><div class="muted">SF Public Works · active physical/context centerlines</div></div><label class="switch"><input id="sToggle" type="checkbox" checked><span></span></label></div>', '<div class="row"><div><div class="label">Street network</div><div class="muted">SF Public Works · active physical/context centerlines</div></div><label class="switch"><input id="sToggle" type="checkbox" checked><span></span></label></div>\n<div class="row"><div><div class="label">Hill steepness</div><div class="muted">Estimated from official 5-ft elevation contours</div></div><label class="switch"><input id="hToggle" type="checkbox" checked><span></span></label></div>', 'hill toggle')
repl('<div class="legend"><span class="ln street-ln"></span><span class="legendtext">Major / arterial street centerline</span><span class="info" title="SF Public Works centerline; visual weight comes from the source classcode field.">ⓘ</span></div>', '<div class="legend"><span class="ln street-ln"></span><span class="legendtext">Major / arterial street centerline</span><span class="info" title="SF Public Works centerline; visual weight comes from the source classcode field.">ⓘ</span></div>\n<div class="legend"><span class="ln" style="border-top:3px solid #aeb7c2"></span><span class="legendtext">Estimated grade &lt;5%</span></div>\n<div class="legend"><span class="ln" style="border-top:3px solid #e9c46a"></span><span class="legendtext">Estimated grade 5–9.9%</span></div>\n<div class="legend"><span class="ln" style="border-top:3px solid #f4a261"></span><span class="legendtext">Estimated grade 10–14.9%</span></div>\n<div class="legend"><span class="ln" style="border-top:3px solid #e76f51"></span><span class="legendtext">Estimated grade 15–19.9%</span></div>\n<div class="legend"><span class="ln" style="border-top:3px solid #9b2226"></span><span class="legendtext">Estimated grade 20%+</span><span class="info" title="Derived estimate, not an official engineering street-grade survey.">ⓘ</span></div>', 'hill legend')
repl('<div class="methoditem"><strong>Street styling</strong><br>Public Works class codes are used only for readability:', '<div class="methoditem"><strong>Hill steepness</strong><br>Derived at build time from DataSF Elevation Contours <span class="code">rnbg-2qxw</span>, which contains 5-foot contour lines based on the San Francisco Elevation Datum. The build samples five points along each street segment, estimates elevation from nearby distinct contour levels, and calculates average absolute elevation change over horizontal street length. This is an <em>estimated average grade</em>, not an official engineering street-grade survey. Confidence reflects contour proximity and the number of distinct nearby contour levels.</div>\n<div class="methoditem"><strong>Street styling</strong><br>Public Works class codes are used only for readability:', 'hill method')
repl('<div><b>Streets</b><span id="ss">Reading embedded bundle…</span></div>', '<div><b>Streets</b><span id="ss">Reading embedded bundle…</span></div>\n<div><b>Hills</b><span id="hs">Reading derived grades…</span></div>', 'hill status')
repl("const S={p:DATA?.precincts||null,s:DATA?.streets||null,m:DATA?.multifamily||null,b:null,n:20,ss:true,sp:true,sm:true,z:1,x:0,y:0,drag:false,lx:0,ly:0};", "const S={p:DATA?.precincts||null,s:DATA?.streets||null,m:DATA?.multifamily||null,b:null,n:20,ss:true,sh:true,sp:true,sm:true,z:1,x:0,y:0,drag:false,lx:0,ly:0};", 'state')
repl('function add(parent,d,cls,f,k){', "const hillGrade=p=>Number(p.estimated_grade_pct),hillConfidence=p=>String(p.grade_confidence||'unknown'),hillClass=p=>{const g=hillGrade(p);if(!Number.isFinite(g))return'hunk';if(g>=20)return'hg20';if(g>=15)return'hg15';if(g>=10)return'hg10';if(g>=5)return'hg5';return'hg0'},hillText=p=>{const g=hillGrade(p);return Number.isFinite(g)?`${g.toFixed(1)}% estimated average grade · ${hillConfidence(p)} confidence`:'grade unavailable'};\nfunction add(parent,d,cls,f,k){", 'hill helpers')
old="function renderS(){sl.replaceChildren();const rank={0:0,5:1,4:2,3:3,2:4,6:5,1:6},fs=[...(S.s?.features||[])].sort((a,b)=>(rank[streetClass(a.properties||{})]??0)-(rank[streetClass(b.properties||{})]??0));fs.forEach(f=>{const d=linePath(f.geometry);if(d)add(sl,d,'st sc'+streetClass(f.properties||{}),f,'s')});sl.style.display=S.ss?'':'none';renderLabels()}"
new="function renderS(){sl.replaceChildren();const rank={0:0,5:1,4:2,3:3,2:4,6:5,1:6},fs=[...(S.s?.features||[])].sort((a,b)=>(rank[streetClass(a.properties||{})]??0)-(rank[streetClass(b.properties||{})]??0));fs.forEach(f=>{const p=f.properties||{},d=linePath(f.geometry),c=streetClass(p),hc=S.sh&&c!==1&&c!==6?' '+hillClass(p):'';if(d)add(sl,d,'st sc'+c+hc,f,'s')});sl.style.display=(S.ss||S.sh)?'':'none';renderLabels()}"
repl(old,new,'render streets')
repl("return`<strong>${esc(name)}</strong>${from||to?`Between ${esc(from||'segment start')} and ${esc(to||'segment end')}<br>`:''}CNN ${esc(cnn)} · ${esc(streetClassName(streetClass(p)))}<br><span style=\"opacity:.82\">${esc(streetNote(p))}</span>`", "return`<strong>${esc(name)}</strong>${from||to?`Between ${esc(from||'segment start')} and ${esc(to||'segment end')}<br>`:''}CNN ${esc(cnn)} · ${esc(streetClassName(streetClass(p)))}<br>${esc(hillText(p))}<br><span style=\"opacity:.82\">${esc(streetNote(p))} Hill value is derived from 5-ft contours, not an engineering survey.</span>`", 'hover')
repl('<br>CNN: ${esc(p.cnn??\'—\')}<br>Class: ${esc(streetClassName(c))}<br>Source layer: ${esc(streetLayer(p))}', '<br>CNN: ${esc(p.cnn??\'—\')}<br>Class: ${esc(streetClassName(c))}<br>Hill estimate: ${esc(hillText(p))}<br>Source layer: ${esc(streetLayer(p))}', 'click')
repl("$('sToggle').onchange=e=>{S.ss=e.target.checked;sl.style.display=S.ss?'':'none';ll.style.display=S.ss?'':'none';renderLabels()};", "$('sToggle').onchange=e=>{S.ss=e.target.checked;renderS()};\n$('hToggle').onchange=e=>{S.sh=e.target.checked;renderS()};", 'toggles')
repl("$('ss').innerHTML=`<span class=\"ok\">${S.s.features.length.toLocaleString()} displayed</span><span class=\"muted\"> · ${srcActive.toLocaleString()} active source; ${excludedN.toLocaleString()} non-street/pseudo excluded</span>`;", "$('ss').innerHTML=`<span class=\"ok\">${S.s.features.length.toLocaleString()} displayed</span><span class=\"muted\"> · ${srcActive.toLocaleString()} active source; ${excludedN.toLocaleString()} non-street/pseudo excluded</span>`;const gc=DATA.meta?.grade_category_counts||{},graded=Number(DATA.meta?.graded_street_count||0),low=Number(DATA.meta?.grade_low_confidence_count||0);$('hs').innerHTML=`<span class=\"ok\">${graded.toLocaleString()} graded</span><span class=\"muted\"> · ${low.toLocaleString()} low/unavailable · 20%+: ${Number(gc['20+']||0).toLocaleString()}</span>`;", 'status init')
repl('Street centerlines are now the common geography for navigation and future hill/closure layers.', 'Street centerlines now carry a derived hill-steepness estimate from official 5-ft elevation contours; future closures can attach to the same segments.', 'banner')
p.write_text(s,encoding='utf-8')
print('patched hill UI')
